bind = '0.0.0.0:5000'
workers = 5
worker_class = 'uvicorn.workers.UvicornWorker'
worker_connections = 1000
keepalive = 5
accesslog = 'access.log'
access_log_format = '%({x-real-ip}i)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
errorlog = 'error.log'
loglevel = 'error'